"""create pegawai table

Revision ID: 565fe8506892
Revises: 
Create Date: 2024-11-28 23:19:32.916227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565fe8506892'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pegawai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pegawai', sa.String(), nullable=True),
    sa.Column('foto_1', sa.String(), nullable=True),
    sa.Column('foto_2', sa.String(), nullable=True),
    sa.Column('foto_3', sa.String(), nullable=True),
    sa.Column('foto_4', sa.String(), nullable=True),
    sa.Column('foto_5', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pegawai_id'), 'pegawai', ['id'], unique=False)
    op.create_index(op.f('ix_pegawai_id_pegawai'), 'pegawai', ['id_pegawai'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pegawai_id_pegawai'), table_name='pegawai')
    op.drop_index(op.f('ix_pegawai_id'), table_name='pegawai')
    op.drop_table('pegawai')
    # ### end Alembic commands ###
